spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/barbearia?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${SERVER_PORT:8085}

app.jwt.secret=H7r#Qm92!ZvLp@4XsTk8$NwU5ByUcDfJ6AgRjMiP
app.jwt.expiration-ms=86400000